import { Schema, model } from "mongoose";

/**
 * Shape of a todo document as stored in MongoDB.
 * Matches the assignment's model example. `description` is absent when empty.
 */
export interface TodoRecord {
  _id: string;
  title: string;
  description?: string;
  done: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const todoSchema = new Schema<TodoRecord>(
  {
    // UUID generated by the domain (TodoId), stored as a string.
    _id: { type: String, required: true },
    title: { type: String, required: true },
    description: { type: String },
    done: { type: Boolean, required: true, default: false },
    // Set by the domain, not by Mongoose (no `timestamps: true`),
    // so Mongoose never overwrites the domain's values.
    createdAt: { type: Date, required: true },
    updatedAt: { type: Date, required: true },
  },
  {
    collection: "todos",
    versionKey: false,
  },
);

// Supports "newest first" listing without an in-memory sort.
// Supports "newest first" listing and paging without an in-memory sort.
todoSchema.index({ createdAt: -1, _id: -1 });

export const TodoModel = model<TodoRecord>("Todo", todoSchema);
