import { randomUUID } from "node:crypto";
import { ValidationError } from "../shared/ValidationError.ts";

const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

/**
 * Identity of a todo.
 *
 * Generated by the domain (not the database) so a todo has its identity
 * from the moment it is created, before it is ever persisted.
 */
export class TodoId {
  private constructor(readonly value: string) {}

  /** Creates a brand-new id for a new todo. */
  static generate(): TodoId {
    return new TodoId(randomUUID());
  }

  /** Wraps an existing id, e.g. from a URL param or the database. */
  static from(value: string): TodoId {
    if (!UUID_PATTERN.test(value)) {
      throw new ValidationError("id", "Invalid todo id");
    }
    return new TodoId(value);
  }

  equals(other: TodoId): boolean {
    return this.value === other.value;
  }

  toString(): string {
    return this.value;
  }
}
